install.packages("shiny")
install.packages("shinyBS")
install.packages("shinyjs")
install.packages("plotly")
install.packages("future")
install.packages("devtools")
install.packages("ggplot2")
install.packages("plyr")
install.packages("gsl")
devtools::install_github("role-model/roleR", ref="main")
devtools::install_github("ajrominger/pika", keep_source = TRUE, force=TRUE)
