install.packages("shiny", version = "1.4.0.2")
install.packages("shinyBS", version = "0.61")
install.packages("shinyjs", version = "2.0.0")
install.packages("plotly", version = "4.9.3")
install.packages("future", version = "1.21.0")
install.packages("devtools")
install.packages("ggplot2")
install.packages("plyr")
install.packages("gsl")
devtools::install_github("role-model/roleR", ref="main")
devtools::install_github("ajrominger/pika", keep_source = TRUE, force=TRUE)

