install.packages("devtools")
install.packages("plotly")
install.packages("ggplot2")
install.packages("shinyjs")
install.packages("plyr")
install.packages("future")
install.packages("gsl")
install.packages("remotes")
remotes::install_github("role-model/roleR", ref="main")
remotes::install_github("ajrominger/pika", keep_source=TRUE, force=TRUE)
remotes::install_github("role-model/roleShiny", ref="main", force=TRUE)

